# Generated by Django 3.2 on 2022-08-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_team_name_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
