# Generated by Django 3.2 on 2022-08-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_plan_end_date'),
        ('lead', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='associated_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='team.team'),
        ),
    ]
